### ISSUE TITLE
Error in npn_allobssp() with rbindlist

### ISSUE THREAD

**Issue by ahhurlbert** [usa-npn/rnpn#14]
Just trying to capture NPN observations for Monarch butterfly (species id 396), but there is an internal error with rbindlist().

Depending on the dates I specify, the details of mismatch of number of columns being rbinded vary...

`out = npn_allobssp(396, startdate='2013-01-01', enddate = '2015-03-15')`
Error in rbindlist(lapply(tt$station_list, data.frame)) : 
  Item 2 has 7 columns, inconsistent with item 1 which has 16 columns. If instead you need to fill missing columns, use set argument 'fill' to TRUE.

`out = npn_allobssp(396, startdate='2015-01-01', enddate = '2015-12-31')`
Error in rbindlist(lapply(tt$station_list, data.frame)) : 
  Item 2 has 14 columns, inconsistent with item 1 which has 16 columns. If instead you need to fill missing columns, use set argument 'fill' to TRUE.

`out = npn_allobssp(396, startdate='2013-01-01', enddate = '2013-12-31')`
Error in rbindlist(lapply(tt$station_list, data.frame)) : 
  Item 2 has 16 columns, inconsistent with item 1 which has 7 columns. If instead you need to fill missing columns, use set argument 'fill' to TRUE.

**Comment by sckott** [comment]
thanks for the report @ahhurlbert 

I'll have a look and get fixed right away

**Comment by sckott** [comment]
looks like the data format has changed too...

**Comment by sckott** [comment]
changes in 652a336bb64ecc91f192a1840b86d838f9f6d4a5 

okay try reinstalling like `devtools::install_github("ropensci/rnpn")`

changed parsing, and giving back list now instead of s4 object for simplicity sake, i don't really like s4 so will probably drop that bit

**Comment by sckott** [comment]
let me know if it works

**Comment by ahhurlbert** [comment]
Yep, looks great. Thanks @sckott!

**Comment by sckott** [comment]
great
