### ISSUE TITLE
see if Lee can fix JSON

### ISSUE THREAD

**Issue by sckott** [usa-npn/rnpn#16]
e.g,. in any request http://www.usanpn.org/npn_portal/species/getSpeciesFilter.json?group_ids[0]=9&group_ids[1]=3&observation_year=2010 the numbers are returned as character

**Comment by sckott** [comment]
@npnlee85 any thoughts

**Comment by npnlee85** [comment]
Unfortunately the framework we're using for jockeying data from the
database wants to treat all fields as strings which then gets incorporated
into the JSON encoding. I can take a look at trying to explicitly casting
numeric values to int/float values, but I'm not sure how quickly I can get
to that. Is there any urgency to the issue?

## 

Lee Marsh
IT Coordinator
National Coordinating Office, USA National Phenology Network
School of Natural Resources and the Environment, University of Arizona
1955 East 6th Street, Tucson, AZ 85721
Phone: (309) 696-6334
www.usanpn.org

**Comment by sckott** [comment]
no, not a rush, just curious if it could be fixed at some point

**Comment by sckott** [comment]
any progress on this @npnlee85  just curious

**Comment by npnlee85** [comment]
Yes. I actually have all the changes ready to provide numeric values as
numbers and not strings, but I'm waiting to complete and test some other
changes on our services before pushing to production.

## 

Lee Marsh
IT Coordinator
National Coordinating Office, USA National Phenology Network
School of Natural Resources and the Environment, University of Arizona
1955 East 6th Street, Tucson, AZ 85721
Phone: (309) 696-6334
www.usanpn.org

On Wed, Jun 15, 2016 at 8:38 AM, Scott Chamberlain <notifications@github.com

**Comment by sckott** [comment]
thanks

**Comment by npnlee85** [comment]
Hi,

Happy to report that this issue should be resolved now. Not sure -- is
there an issue ticket I can close out, or?

## 

Lee Marsh
IT Coordinator
National Coordinating Office, USA National Phenology Network
School of Natural Resources and the Environment, University of Arizona
1955 East 6th Street, Tucson, AZ 85721
Phone: (309) 696-6334
www.usanpn.org

On Wed, Jun 15, 2016 at 9:56 AM, Scott Chamberlain <notifications@github.com

**Comment by sckott** [comment]
@npnlee85 awesome, thanks! 

> is there an issue ticket I can close out, or?

yep, this one, i'll close it now
