### ISSUE TITLE
getObservationsForSpeciesByDay is gone?

### ISSUE THREAD

**Issue by sckott** [usa-npn/rnpn#18]
Hi @npnlee85 - seems that the `/getObservationsForSpeciesByDay` is gone. Is that right? If so, what do we use now?

in docs theres `/getObservations` but even the e.g., for that doesn't work

**Comment by npnlee85** [comment]
It's true, no one was using that function so we got rid of it. There's a
few possibilities, but all would require handling the response data
differently.

1) getObservations
https://docs.google.com/document/d/1yNjupricKOAXn6tY1sI7-EwkcfwdGUZ7lxYv7fcPjO8/pub#h.w0nctgedhaop

Probably the best option. Can filter to a particular species, but results
would need to be ordered and counted by date.

2) getAllObservationsForSpecies
https://docs.google.com/document/d/1yNjupricKOAXn6tY1sI7-EwkcfwdGUZ7lxYv7fcPjO8/pub#h.j0m56c1jdmf4
Provides the same info, but also does break the data down by phenophase,
location and status value so response would have to parsed, and per-day
counts re-tabulated.

As for the example getObservations call ... is working okay for me, but I
was in the docs editing things today, so perhaps something went awry.

## 

Lee Marsh
IT Coordinator
National Coordinating Office, USA National Phenology Network
School of Natural Resources and the Environment, University of Arizona
1955 East 6th Street, Tucson, AZ 85721
Phone: (309) 696-6334
www.usanpn.org

On Thu, Sep 15, 2016 at 1:37 PM, Scott Chamberlain <notifications@github.com

**Comment by sckott** [comment]
Thanks. Now that eg works that I said didn't work before, must have been an edit. 

i like the 1st option, i'll try that
