### ISSUE TITLE
npn_download_status_data error 

### ISSUE THREAD

**Issue by tdlan80** [usa-npn/rnpn#28]
I was extracting status and intensity data via the following script
`eastUS0921V3_csv <-
  npn_download_status_data(
    request_source = "ERENbiodiversity", 
    years = c(2009:2021),
    coords = c ( lower_left_lat = 24.10487, lower_left_long = -95.1356, upper_right_lat = 48.73317, upper_right_long = -61.56138),
    email = "tsurasinghe@bridgew.edu",
    download_path = "eastUS0921_V3.csv")`

the data extraction preceded fine until the following message in my console:

> Found 2110000 records...closing curl input connection.
Service is currently unavailable. Please try again later!
Warning message:
In readLines(con, n = pagesize, encoding = "UTF-8") :
  incomplete final line found on 'https://www.usanpn.org/npn_portal//observations/getObservations.ndjson?'

I know that the last two lines are warnings but not sure what that means? 

And i am not sure what the 'service unavailable...' message means. I do have a CSV file saved in my local drive.  Still, I would like to know what these error messages are.

**Comment by alyssarosemartin** [comment]
I think that your download was interrupted - the Service is Unavailable message appears when the server is not reached - and then the "incomplete final lines" suggests that not all the data came through. I would check the final lines of your downloaded CSV, and also just try this call again, to have it run without an interruption. 2M is a lot of records to grab at once (more chance of an interruption), I would suggest pairing down a bit (only certain species) or grabbing year by year.

**Comment by tdlan80** [comment]
I chucked the year into three parts and re-ran. no errors or warning this time. it look a while to complete but the download it complete.
