### ISSUE TITLE
Please remove dependencies on **rgdal**, **rgeos**, and/or **maptools**

### ISSUE THREAD

**Issue by rsbivand** [usa-npn/rnpn#30]
This package depends on (depends, imports or suggests) **raster** and one or more of the retiring packages **rgdal**, **rgeos** or **maptools** (https://r-spatial.org/r/2022/04/12/evolution.html). Since **raster** `3.6.3`, all use of external FOSS library functionality has been transferred to **terra**, making the retiring packages very likely redundant. It would help greatly if you could remove dependencies on the retiring packages as soon as possible.

**Comment by rsbivand** [comment]
Please urgently see https://r-spatial.org/r/2022/12/14/evolution2.html, https://rsbivand.github.io/csds_jan23/bivand_csds_ssg_230117.pdf and perhaps view https://www.youtube.com/watch?v=TlpjIqTPMCA&list=PLzREt6r1NenmWEidssmLm-VO_YmAh4pq9&index=1. Your package may start failing CRAN checks as soon as June 2023, when **sp** changes from business-as-usual (evolution status 0) to evolution status 2, that is using **sf** in place of **rgdal**.

**Comment by rsbivand** [comment]
Further see https://r-spatial.org/r/2023/04/10/evolution3.html.

**Comment by yiluansong** [comment]
I strongly echo this.

**Comment by rsbivand** [comment]
See also https://r-spatial.org/r/2023/05/15/evolution4.html. Action is needed urgently.

**Comment by Aariq** [comment]
I found this in `cran-comments.md`:
>While rgdal isn't used directly, the raster package which is directly used
has dependencies on rgdal that will causes tests to fail if the package is
not installed on the system.

If this is true, you might be able to address this by just removing `rgdal` from the Imports field in DESCRIPTION and removing `library(rgdal)` from the vignettes.  Although `raster` has been superseded by `terra`, it's not going away. The version of `raster` on CRAN no longer depends on `rgdal` (in fact, it depends on `terra`).

**Comment by rsbivand** [comment]
@Aariq exactly what I wrote in December, for all purposes `terra` can replace `rgdal`.

**Comment by rsbivand** [comment]
Three months to  go before package failure; `rgdal` will be withdrawn in October 2023.

**Comment by Aariq** [comment]
Thanks, we're working on it!

**Comment by Aariq** [comment]
Closed with #31

**Comment by rsbivand** [comment]
Thanks, looks OK when tested without retiring packages on the library path: 
[00check.log](https://github.com/usa-npn/rnpn/files/12282714/00check.log)

**Comment by alyssarosemartin** [comment]
This is now taken care of, thanks!
