### ISSUE TITLE
Service down?

### ISSUE THREAD

**Issue by Peter9192** [usa-npn/rnpn#33]
Not sure where to report this, but when I tried using rnpn, it seems the service is down. For example:

```R
> library(rnpn)
> npn_species()
Service is unavailable. Try again later!
# A tibble: 1 × 1
  nodata
  <chr>
1 servicedown
```

**Comment by lgamador** [comment]
Hi! I got something similar and was wondering the same thing.

**Comment by jeffswitzer** [comment]
Hello, we were shifting some services to new servers.

I've committed a change that should fix the issue:
https://github.com/usa-npn/rnpn/blob/master/R/zzz.R#L117

Hopefully this helps!

**Comment by Peter9192** [comment]
Thanks! I can confirm this fixes my issue. I had to install the development version. 

Do you want to keep the issue open until it's also available on CRAN?
