### ISSUE TITLE
`npn_stations_by_state()` returns empty string

### ISSUE THREAD

**Issue by Aariq** [usa-npn/rnpn#37]
This function currently points to "https://services.usanpn.org/npn_portal/stations/getStationCountByState.json" which appears to be empty.

**Comment by Aariq** [comment]
Sounds like this is an API issue because the xml version works

**Comment by jeffswitzer** [comment]
The json version should work now https://services.usanpn.org/npn_portal/stations/getStationCountByState.json

**Comment by Aariq** [comment]
Can confirm it works now.  I'll un-skip that test in the next PR
