### ISSUE TITLE
Write vignette for package

### ISSUE THREAD

**Issue by sckott** [usa-npn/rnpn#6]

**Comment by maelle** [comment]
in that vignette and in the README it'd be nice to write about the scope of the database (it's an US national database, but is there data for outside the US?).

Besides, I imagine there's some potential for very nice visualizations in that data?

**Comment by sckott** [comment]
Right, scope would be good, I don't know about outside the US, that'd be a good question for @npnlee85 

Yes, agreed on potential for visualizations!

**Comment by maelle** [comment]
Ping me when you make the PR, happy to provide my naive feedback after @sckott provides his expert feedback 😉

**Comment by npnlee85** [comment]
Vignettes added to the project.
