### ISSUE TITLE
Add use case examples / unexpected error

### ISSUE THREAD

**Issue by cboettig** [usa-npn/rnpn#8]
This whole package looks pretty amazing.  

It seems like it wouldn't be too difficult to replicate some figures from the literature in order to illustrate this package use.  For instance, I thought this one might make a splashy example: 

http://www.nature.com/nature/journal/v394/n6696/abs/394839b0.html

After looking up the species id for the red lilac successfully, I tried: 

``` coffee
out <- getallobssp(speciesid = 35, startdate="1960-01-01", enddate="1994-01-01")
```

and got this error

```
Error in data.frame(phenophase_id = "76", phenophase_name = "First leaf",  : 
  arguments imply differing number of rows: 1, 0
```

(Provided this works, it would be fun to update the original figure with data since 1994 as well...)

Some of Lizzie's papers might be nice potential examples too: https://www.usanpn.org/biblio?f[author]=4604

**Comment by npnlee85** [comment]
Package has this error fixed, and includes vignettes with a number of examples not unlike the graph provided in the linked paper. Also it's now possible to use the package to pull the Spring Index values directly!
